var body = document.getElementsByTagName('body')[0];
var d = document.createElement('div');
d.className = 'topContainer';
d.style.backgroundColor = 'whitesmoke';
var i = document.createElement('img');
i.src = 'googlelogo.png';
d.appendChild(i);
body.appendChild(d);
var d1 = document.createElement('div');
d1.className = 'searchTools';
var ip = document.createElement('input');
ip.type = 'text';
ip.value = 'google search results page';
d1.appendChild(ip);
d.appendChild(d1);
body.appendChild(d);
var ul = document.createElement('ul');
ul.className = 'searchToolOptions';
var li = document.createElement('li');
li.className = 'left active';
var a = document.createElement('a');
a.className = 'searchToolOption';
a.href = '#';
a.innerHTML = 'All';
li.appendChild(a);
ul.appendChild(li);
var li = document.createElement('li');
li.className = 'left';
var a = document.createElement('a');
a.className = 'searchToolOption';
a.href = '#';
a.innerHTML = 'Images';
li.appendChild(a);
ul.appendChild(li);
var li = document.createElement('li');
li.className = 'left';
var a = document.createElement('a');
a.className = 'searchToolOption';
a.href = '#';
a.innerHTML = 'News';
li.appendChild(a);
ul.appendChild(li);
var li = document.createElement('li');
li.className = 'left';
var a = document.createElement('a');
a.className = 'searchToolOption';
a.href = '#';
a.innerHTML = 'Videos';
li.appendChild(a);
ul.appendChild(li);
var li = document.createElement('li');
li.className = 'left';
var a = document.createElement('a');
a.href = '#';
a.innerHTML = 'More';
li.appendChild(a);
ul.appendChild(li);
var li = document.createElement('li');
li.className = 'right';
var a = document.createElement('a');
a.className = 'searchToolOption';
a.href = '#';
a.innerHTML = 'Tools';
li.appendChild(a);
ul.appendChild(li);
var li = document.createElement('li');
li.className = 'right';
var a = document.createElement('a');
a.className = 'searchToolOption';
a.href = '#';
a.innerHTML = 'Settings';
li.appendChild(a);
ul.appendChild(li);
d1.appendChild(ul);
d.appendChild(d1);
body.appendChild(d);

var ul = document.createElement('ul');
ul.className = 'accountOptions';
var li = document.createElement('li');
var a = document.createElement('a');
a.href = '#';
var i = document.createElement('i');
i.className = 'fas fa-th';
a.appendChild(i);
li.appendChild(a);
ul.appendChild(li);
var li = document.createElement('li');
var a = document.createElement('a');
a.href = '#';
var i = document.createElement('i');
i.className = 'fas fa-bell';
a.appendChild(i);
li.appendChild(a);
ul.appendChild(li);
var li = document.createElement('li');
var a = document.createElement('a');
a.href = '#';
var i = document.createElement('i');
i.className = 'fas fa-user-circle';
a.appendChild(i);
li.appendChild(a);
ul.appendChild(li);

d.appendChild(ul);
body.appendChild(d);

var d = document.createElement('div');
d.className = 'searchResults';
var p = document.createElement('p');
p.className = 'numberOfResults';
p.innerHTML = 'About 866,000,000 results (0.77 seconds)';
d.appendChild(p);
body.appendChild(d);

//...1

var d1 = document.createElement('div');
d1.className = 'result';
var h2 = document.createElement('h2');
h2.innerHTML = '<a>Elements of Google Search Engine Results Page <span style=\'font - size: 18 px;\'>&#8226;</span> SEO for beginners...</a>';
d1.appendChild(h2);
d.appendChild(d1);
body.appendChild(d);
var a = document.createElement('a');
a.className = 'link';
a.href = '#';
a.innerHTML = 'https://yoast.com > SEO blog > SEO basics';
d1.appendChild(a);
d.appendChild(d1);
body.appendChild(d);
var p = document.createElement('p');
p.innerHTML = '<span style=\'color:lightslategray\'>Feb 26, 2018</span> - If you <b>Google</b> something you\'ll end up on the <b>Google Search</b> Engine <b>Results Page.</b>What does this <b>page</b> show? Which elements do you see, ...';
d1.appendChild(p);
d.appendChild(d1);
body.appendChild(d);

//..2

var d1 = document.createElement('div');
d1.className = 'result';
var ip = document.createElement('input');
ip.className = 'input';
ip.placeholder = 'People also ask';
d1.appendChild(ip);
var s = document.createElement('select');
s.className = 'i';
var o = document.createElement('option');
o.innerHTML = 'What is a Google search results page?';
s.appendChild(o);
d1.appendChild(s);
var s = document.createElement('select');
s.className = 'i';
var o = document.createElement('option');
o.innerHTML = 'What do Google search results mean?';
s.appendChild(o);
d1.appendChild(s);
var s = document.createElement('select');
s.className = 'i';
var o = document.createElement('option');
o.innerHTML = 'What is SERP SEO?';
s.appendChild(o);
d1.appendChild(s);
var s = document.createElement('select');
s.className = 'i';
var o = document.createElement('option');
o.innerHTML = 'What is a snippet in Google?';
s.appendChild(o);
d1.appendChild(s);

d.appendChild(d1);
body.appendChild(d);

//...3

var d1 = document.createElement('div');
d1.className = 'result';
var h2 = document.createElement('h2');
h2.innerHTML = '<a>Search engine results page - Wikipedia</a>';
d1.appendChild(h2);
d.appendChild(d1);
body.appendChild(d);
var a = document.createElement('a');
a.className = 'link';
a.href = '#';
a.innerHTML = 'https://en.wikipedia.org/wiki/Search_engine_results_page';
d1.appendChild(a);
d.appendChild(d1);
body.appendChild(d);
var p = document.createElement('p');
p.innerHTML = 'Search Engine Results <b>Pages</b> (SERP) are the <b>pages</b> displayed by search engines in response....Rich snippets are displayed by <b>Google</b> in the <b>search results pages</b> when a website contains content in structured data markup. Structured data...';
p.innerHTML += '<p style="color:rgba(0, 0, 139, 0.76);font-family: Arial, Helvetica, sans-serif;font-size: 12px;line-height: 8px;"><b>Components . Search query . Organic results . Rich snippets</b></p>';
d1.appendChild(p);
d.appendChild(d1);
body.appendChild(d);

//...4

var d1 = document.createElement('div');
d1.className = 'result';
var h2 = document.createElement('h2');
h2.innerHTML = '<a>2018\'s Guide to Google\'s Search Engine Results Page (SERP) - Oberlo</a>';
d1.appendChild(h2);
d.appendChild(d1);
body.appendChild(d);
var a = document.createElement('a');
a.className = 'link';
a.href = '#';
a.innerHTML = 'https://www.oberlo.com > Blog';
d1.appendChild(a);
d.appendChild(d1);
body.appendChild(d);
var p = document.createElement('p');
p.innerHTML = '<span style=\'color:lightslategray\'>Jul 10, 2018</span>- These new SERP features - SERP is shorthand for <b>search</b> engine <b>results page</b> - have improved the experience for users, but they\'re also...';
d1.appendChild(p);
d.appendChild(d1);
body.appendChild(d);

//..5

var d1 = document.createElement('div');
d1.className = 'result';
var h2 = document.createElement('h2');
h2.innerHTML = '<a>SERP: The 2018 Guide To Google Search Engine Results</a>';
d1.appendChild(h2);
d.appendChild(d1);
body.appendChild(d);
var a = document.createElement('a');
a.className = 'link';
a.href = '#';
a.innerHTML = 'https://ignitevisibility.com/serp/';
d1.appendChild(a);
d.appendChild(d1);
body.appendChild(d);
var p = document.createElement('p');
p.innerHTML = '<span style=\'color:lightslategray\'>May 1, 2018</span> - SERP refers to a <b>search</b> engine result <b>page</b> - the <b>page</b>  that appears with a user\'s <b>results</b> when they type a <b>search</b> into <b>Google</b> (or any <b>search...</b>';
d1.appendChild(p);
d.appendChild(d1);
body.appendChild(d);